Iter13
ProvoloneStein/go-url-shortener-service pull request #13
Opened 2023-06-12 13:13 UTC by ProvoloneStein

2023-06-17 14:53 UTC, s-shpak requested changes

2023-06-17 14:53 UTC, s-shpak commented on internal/app/handlers/shortener.go
> +	res, serviceErr := h.services.CreateShortURL(ctx, string(body))
Не совсем понимаю, зачем давать ошибке имя отличное от `err` здесь

2023-06-17 14:53 UTC, s-shpak commented on internal/app/repositories/file.go
> +	case <-ctx.Done():
Лучше сделать код более плоским:

```go
select {
case <-ctx.Done():
...
default
}
for key, val := range r.store
...
```

2023-06-17 14:53 UTC, s-shpak commented on internal/app/repositories/file.go
> +		return "", errors.New("url not found")
Я бы:
1. Создал дополнительную ошибку, которая указывала на то, что `url` не найдена (чтобы легко было проверять на верхнем уровне, что ошибка связана именно с этим)
2. Включал в сообщение об ошибке ключ, по которому `url` искалась

2023-06-17 14:53 UTC, s-shpak commented on internal/app/repositories/local.go
> +			time.Sleep(time.Second)
Зачем эта задержка?

2023-06-17 14:53 UTC, s-shpak commented on internal/app/repositories/local.go
> +			if err == nil {
А что если ошибка не `nil`?

2023-06-17 14:53 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +type PostgresRepository struct {
Не вижу смысла в названии структуры указывать, что эта реализация взаимодействует с постгресом

2023-06-17 14:53 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +		"(id BIGSERIAL PRIMARY KEY, url TEXT UNIQUE NOT NULL, shorten TEXT UNIQUE NOT NULL)")
Опицонально: я бы не использовал `TEXT`: https://brandur.org/text

2023-06-17 14:53 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +		"(id BIGSERIAL PRIMARY KEY, url TEXT UNIQUE NOT NULL, shorten TEXT UNIQUE NOT NULL)")
Опционально: я бы не использовал `TEXT`: https://brandur.org/text

2023-06-17 14:53 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +		return err
Ошибки стоит оборачивать

2023-06-17 14:53 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +func ConntectPG(dsnString string) (*sql.DB, error) {
А зачем ты разнес подключение к БД и конструктор `NewPostgresRepository`?

2023-06-17 14:53 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +		shortURL := randomString()
Я бы убрал эту бизнес-логику на верхний слой

2023-06-17 14:53 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +		shortRow := r.db.QueryRowContext(ctx, "SELECT id FROM shortener WHERE  shorten = $1", shortURL)
Если ты используешь два запроса к БД в одной функции, то лучше использовать транзакции. Но на самом деле можно обойтись одним запросом

2023-06-17 14:53 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +					if _, err := tx.ExecContext(ctx, "INSERT INTO shortener (url, shorten) VALUES($1, $2)", val.URL, shortURL); err == nil {
Сейчас это не батчинг, это запись данных в БД по очереди. В идеале, ты должен делать фиксированное количество запросов к БД (один, например), которое не должно зависеть от количества отправляемых данных. Для батчинга можно:
1. перейти на `pgx` вместо `db/sql`
2. формировать запрос самому
3. использовать библиотеку типа `sqlx` или `squirrel`

2023-06-18 18:20 UTC, ProvoloneStein commented on internal/app/repositories/postgres.go
> +		return err
Тут небольшой вопрос:
Я так понял , что надо обрабатывать ошибки из сторонних библиотек, а из стандартных не обязательно
или надо обернуть потому что драйвер кастомный у бд?

2023-06-22 16:08 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +		return err
Лучше оборачивать ошибки и из стандартной, и из сторонних библиотек: это позволяет легко локализовать проблему по тексту ошибки

2023-06-22 16:20 UTC, s-shpak requested changes

2023-06-22 16:20 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +func ConntectPG(dsnString string) (*sqlx.DB, error) {
Теперь эту функцию необязательно экспортировать

2023-06-22 16:20 UTC, s-shpak commented on internal/app/repositories/file.go
> +	return "", NewValueError(shortURL, ErrURLNotFound)
Я не имел в виду такую обертку, скорее что-то типа:

```suggestion
	return "", fmt.Errorf("%w: %s", ErrURLNotFound, shortURL)
```

Это и добавляет тип к ошибке, и пояснение о ее происхождении

2023-06-23 13:43 UTC, ProvoloneStein commented on internal/app/repositories/postgres.go
> +		shortURL := randomString()
уф! метод Create без проблем вытащил
С batch create по итогу решения не придумал пока
если я буду генерить список урлов в сервисе, а потом валидировать  в репозитории - получится очень долго и странно

вижу решение как прокидывание в сервис метода, который добавит к входящим данным шорт урлы, и передавать их список в батч, но это разными транзакциями будет 
еще хотелось бы урлджоин из самого батча вынести, но не хочется лишний раз в цикле бегать по списку

2023-06-23 15:55 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +		shortURL := randomString()
Я не очень понимаю в чем разница: ты генерируешь набор ссылок, передаешь их на нижний уровень, получаешь ответ, если это ошибка перегенерируешь набор (или одну конкретную ссылку)

Но можно пока оставить и так, но зарефакторить позже. Если хочешь сделать так, то зарезолвь этот коммент

2023-06-23 15:55 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +type PostgresRepository struct {
Обрати внимание на этот комментарий

2023-06-23 15:59 UTC, s-shpak requested changes

2023-06-23 15:59 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +	tx, err := r.db.BeginTxx(ctx, nil)
Транзакцию надо закрывать всегда. Лучше всего вызвать `defer tx.Commit()` на строке 86, а в случае ошибки вызывать `tx.Rollback()` (вызов `Commit` после `Rollback` не делает ничего)

2023-06-23 16:58 UTC, s-shpak requested changes

2023-06-23 16:58 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +		return shortRes, ErrorUniqueViolation
А здесь `tx.Rollback`?

2023-06-23 17:08 UTC, ProvoloneStein commented on internal/app/repositories/postgres.go
> +		return shortRes, ErrorUniqueViolation
хм, справедливо! сначала думал, что раз результат такой же, то откатывать не надо, но с ролбеком надежней будет

2023-06-23 17:33 UTC, s-shpak approved these changes

2023-06-25 19:35 UTC, merged