Iter15
ProvoloneStein/go-url-shortener-service pull request #15
Opened 2023-06-27 11:47 UTC by ProvoloneStein

2023-06-29 14:35 UTC, s-shpak requested changes

2023-06-29 14:35 UTC, s-shpak commented on cmd/shortener/main.go
> +	switch {
Насколько я понимаю, это связано с линтером, думаю что на 1-1 обсудим

2023-06-29 14:35 UTC, s-shpak commented on internal/app/handlers/middlewares.go
> +			if err != nil {
Тут стоит проверить тип ошибки, если не `ErrNoCookie`, то ее стоит обработать по-другому

2023-06-29 14:35 UTC, s-shpak commented on internal/app/handlers/utils.go
> +		return "", errors.New("user id is of invalid type")
Можно также записать тип токена и проверить, что при извлечении из контекста он не nil

2023-06-29 14:35 UTC, s-shpak commented on internal/app/handlers/shorten.go
> +			w.WriteHeader(http.StatusInternalServerError)
Здесь ошибку можно залогировать

2023-06-29 14:35 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +			err = errDefer
Эту ошибку можно было бы просто залогировать, чтобы не потерять оригинальную ошибку

2023-06-29 14:35 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +	case <-ctx.Done():
В принципе, эта проверка не нужна, т.к. `ExecContext` и так ее сделает

2023-06-29 14:35 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +	_, err := r.db.ExecContext(ctx, "UPDATE shortener set deleted = True WHERE user_id LIKE $1 and shorten = any ($2::text[])", userID, data)
Зачем для сравнения `user_id` использовать `LIKE`?

2023-06-29 14:35 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +func (r *DBRepository) DeleteUserURLsBatch(ctx context.Context, userID string, data []string) error {
Количество запросов может быть очень большим, что может положить БД или заставить сервис работать не оптимально. Подумай, как можно их ограничить (здесь описано: https://github.com/jmoiron/sqlx/issues/300)

2023-06-29 14:35 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +func (r *DBRepository) ValidateUniqueUser(ctx context.Context, userID string) error {
В принципе, можно использовать `uuid` например, что будет гарантировать уникальность пользователя

2023-06-29 14:35 UTC, s-shpak commented on internal/app/services/auth.go
> +	signingKey = "qrkjk#4#%35FSFJlja#4353KSFjH"
Я понимаю, что в ТЗ этого нет, но давай позволим передавать ключ серверу при его старте

2023-07-04 20:33 UTC, ProvoloneStein commented on internal/app/repositories/postgres.go
> +			err = errDefer
(не конкретно к этмоу комменту)
я пооборачивал ошибки, но почти уверен, что сделал это неправильно. буду рад если прокомментишь этот момент хХ

2023-07-06 10:24 UTC, s-shpak commented on internal/app/handlers/utils.go
> +		return "", fmt.Errorf("user id is of invalid type %s", reflect.TypeOf(value))
Для записи типа можно использовать `%T`

2023-07-06 10:24 UTC, s-shpak commented on internal/app/handlers/middlewares.go
> +					if err = gz.Close(); err != nil {
Сейчас ты теряешь оригинальную ошибку, т.к. ты присваиваешь переменной, где она хранится новое значение (это относится и к другим defer). Ты можешь зашедоуить эту переменную, если используешь `:=`

2023-07-06 10:24 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +			err = errDefer
Вроде бы все верное - ты оборачиваешь ошибки, добавляя к ним сообщение и используя `%w`, если ты имел в виду что-то другое - напиши

2023-07-06 10:27 UTC, s-shpak requested changes

2023-07-06 10:27 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +		return nil, fmt.Errorf("repository: ошибка при подключении к базе данных: %w", err)
Не обязательно добовлять `repository` -- я бы просто добавлял еще сообщение на верзнем слое, типа (`не удалось инициализировать подключение к БД: %w`), где `%w` -- ошбика, полученная от слоя БД

2023-07-06 21:16 UTC, ProvoloneStein commented on internal/app/repositories/postgres.go
> +		return nil, fmt.Errorf("repository: ошибка при подключении к базе данных: %w", err)
да, вот как раз про обертку repository (конкретно в функции defaultRepoErrWrapper) у меня в целом сомнения были. Изначально выбрал такое оборачивание, потому что посчитал, что выносить ошибки, которые встречаются по 1-2 раза в проекте в константы/функции не очень хорошая идея

если я правильно понял суть таких оберток ошибок, то в проектах бОльшего размера у меня бы появился некий словарь оберток типо "ошибка при запросе к бд", "ошибка при десериализации данных" и тд
и условная функция defaultRepoErrWrapper бы заменилась на условные QueryRepoErrWrapper,  DeserializationRepoErrWrapper и тд

2023-07-06 21:27 UTC, ProvoloneStein commented on internal/app/repositories/postgres.go
> +		return nil, fmt.Errorf("repository: ошибка при подключении к базе данных: %w", err)
а по поводу конкретно этого коммента у меня как раз на уровне мейна эта ошибка примерно так и логгируется через fatal :D

2023-07-07 02:44 UTC, s-shpak commented on internal/app/repositories/postgres.go
> +		return nil, fmt.Errorf("repository: ошибка при подключении к базе данных: %w", err)
Как правило определять много функций для генерации ошибок не требуется: повторяющихся дейтсвий не так много,, потому редко когда приходится генераизировать создание сообщения об ошибке. Если это необходимо, то я часто вижу, что добавляется доп. функция для этого

2023-07-07 02:45 UTC, s-shpak approved these changes

2023-08-19 16:22 UTC, merged