Iter20
ProvoloneStein/go-url-shortener-service pull request #20
Opened 2023-09-02 11:23 UTC by ProvoloneStein

2023-09-02 22:08 UTC, s-shpak requested changes

2023-09-02 22:08 UTC, s-shpak commented on cmd/shortener/main.go
> +		file, repoInitErr := os.OpenFile(config.FileStorage, os.O_CREATE|os.O_RDWR, filePerms)
Поясни, пожалуйста, зачем называть переменную с ошибкой здесь особенным образом?

2023-09-02 22:08 UTC, s-shpak commented on cmd/staticlint/doc.go
Кажется, что не стоит копировать весь текст сюда: может лучше дать ссылку на документацию staticcheck ?

2023-09-02 22:08 UTC, s-shpak commented on cmd/staticlint/main.go
> +					if fmt.Sprintf("%s.%s", pkgExpr.Name, funExpr.Sel.Name) == "os.Exit" {
Лучше не вызывать здесь `fmt.Sprintf` - это дорого. Достаточно проверить `pkgExpr == "os"` и `funExpr.Sel.Name == "Exit"`

2023-09-02 22:08 UTC, s-shpak commented on cmd/staticlint/main.go
> +	expr := func(x *ast.ExprStmt) {
Я бы не стал создавать анонимную функцию для этой логики. Почему бы не вынести ее в обычную функцию?

2023-09-02 22:08 UTC, s-shpak commented on cmd/staticlint/main.go
> +		if call, ok := x.X.(*ast.CallExpr); ok {
Очень много вложенности. Может можно как-то сделать код более плоским

2023-09-02 22:08 UTC, s-shpak commented on internal/app/handlers/handlers_test.go
> +		if deferErr := resp.Body.Close(); deferErr != nil {
Если ты никак не обрабатываешь ошибку, то можно просто ее игнорировать: `_ = resp.Body.Close()`. Но лучше ее хотя бы залогировать

2023-09-06 22:36 UTC, ProvoloneStein commented on cmd/shortener/main.go
> +		file, repoInitErr := os.OpenFile(config.FileStorage, os.O_CREATE|os.O_RDWR, filePerms)
shadow анализатор ругается
других решений исправить не придумал ._.

2023-09-13 20:42 UTC, ProvoloneStein commented on cmd/shortener/main.go
> +		file, repoInitErr := os.OpenFile(config.FileStorage, os.O_CREATE|os.O_RDWR, filePerms)
хм думал попробовать игнор подрубить, но не понял как ._.

2023-09-14 13:21 UTC, s-shpak commented on cmd/shortener/main.go
> +		file, repoInitErr := os.OpenFile(config.FileStorage, os.O_CREATE|os.O_RDWR, filePerms)
Это одна из причин, почему я отключал `shadow`: с ним код получается неидиоматическим (в го шэдоуить переменные - нормально, на мой взгляд). Я бы посоветовал тебе либо отключить эту проверку, либо добавить игноры как здесь: https://golangci-lint.run/usage/false-positives/#nolint-directive

2023-09-14 13:23 UTC, s-shpak requested changes
См. комментарий про shadow

2023-09-15 08:02 UTC, s-shpak requested changes
Осталось поправить замеачния `golangci-lint`

2023-09-15 08:56 UTC, s-shpak approved these changes
LGTM!

2023-09-19 16:49 UTC, merged