Iter9
ProvoloneStein/go-url-shortener-service pull request #9
Opened 2023-05-28 21:33 UTC by ProvoloneStein

2023-06-04 11:18 UTC, s-shpak requested changes

2023-06-04 11:18 UTC, s-shpak commented on internal/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Глобальные переменные не нужны. Инициализируй логгер, возвращай из функции и передавай логгер туда, куда нужно

2023-06-04 11:18 UTC, s-shpak commented on internal/logger/logger.go
> +		return err
Ошибки из сторонних бибиотек или пакетов нужно оборачивать

2023-06-04 11:18 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +	router.Use(gzipReaderHandler)
`gzipWriter` и `gzipReader` лучше объединить в один middleware

2023-06-04 11:18 UTC, s-shpak commented on internal/app/handlers/middlewares.go
> +						io.WriteString(w, err.Error())
Не стоит отправлять внутренние ошибки пользователю

2023-06-04 11:18 UTC, s-shpak commented on internal/app/handlers/middlewares.go
> +					if err != nil {
Ошибку лучше залогировать

2023-06-04 11:18 UTC, s-shpak commented on internal/app/handlers/shorten.go
> +	if err != nil {
Неожиданные ошибки стоит логировать

2023-06-04 11:18 UTC, s-shpak commented on internal/app/repositories/file.go
> +		repo.uuid, _ = strconv.Atoi(record.UUID)
Ошибки надо проверять

2023-06-04 11:18 UTC, s-shpak commented on internal/app/repositories/file.go
> +		return nil, err
Надо различать `EOF` и другие ошибки, чтобы понимать, ожидаемая ли это ошика или нет

2023-06-04 11:18 UTC, s-shpak commented on internal/logger/middlewares.go
> +		start := time.Now()
Таймер лучше стартовать перед вызовом хендлера

2023-06-08 08:25 UTC, ProvoloneStein commented on internal/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Ок! Изначально делал как в уроке

2023-06-08 11:59 UTC, s-shpak requested changes

2023-06-08 11:59 UTC, s-shpak commented on internal/app/handlers/middlewares.go
> +		writer:
Поосторожнее с `goto`: они сильно усложняют код. К тому же эта часть этой функции располагается на четырех уровнях, это не очень симпатично. Я не прошу тебя переделывать, но к этому могут придираться в реальных проектах. Если не захочешь рефакторить, то просто зарезолвь этот комментарий

2023-06-08 11:59 UTC, s-shpak commented on internal/app/handlers/middlewares.go
> +			// TODO если успею, то надо добавить провеку размера ответа (пока не понял как))
При мердже старайся убирть такие TODO (можно оставить, если оставляешь на следующий спринт)

2023-06-08 11:59 UTC, s-shpak commented on internal/app/repositories/file.go
> +	switch {
Я бы не стал использовать здесь `switch`: провер на ошибки через if, т.к. основную логику лучше делать как можно более плоской

2023-06-08 11:59 UTC, s-shpak commented on internal/logger/middlewares.go
> +		start := time.Now()
Нет, я не это имел в виду. Я имел в виду, что таймер надо запускать на строчку выше вызова "h.ServeHTTP". В текущей реализации значение `start` будет одинаковым для всех запросов, что неправильно

2023-06-08 11:59 UTC, s-shpak commented on internal/app/handlers/shorten.go
> +		http.Error(w, err.Error(), http.StatusUnprocessableEntity)
Это внутренняя ошибка. Отдавай лучше просто `http.InternalServerError`, без пояснений пользователю о том, что произошло

2023-06-08 11:59 UTC, s-shpak commented on internal/app/handlers/shotener.go
`shotener.go` -> `shortener.go`

2023-06-08 11:59 UTC, s-shpak commented on internal/app/handlers/shotener.go
> +		h.logger.Error("ошибка при создании url", zap.Error(err))
Лучше вызвать `return` после

2023-06-08 11:59 UTC, s-shpak commented on internal/app/repositories/file.go
> +			logger.Error("Ошибка при попытке иницилизации репозитория", zap.Error(err))
Можно детектить, что содержимое закончилось и не писать в лог ошибку при этом (иначе при каждом запуске приложение будет выводить ошибку)

2023-06-08 11:59 UTC, s-shpak commented on internal/app/repositories/file.go
> +			logger.Error("Ошибка при получения uuid записи", zap.Error(err))
Кажется, что в случае ошибки файл можно считать битым и завершать выполнение программы

2023-06-08 22:33 UTC, ProvoloneStein commented on internal/app/repositories/file.go
> +			logger.Error("Ошибка при попытке иницилизации репозитория", zap.Error(err))
если правильно понял, то так вроде и делается. ReadString просто не возвращает при EOF ошибку

2023-06-08 22:34 UTC, ProvoloneStein commented on internal/app/handlers/middlewares.go
> +			// TODO если успею, то надо добавить провеку размера ответа (пока не понял как))
ага, к следующему спринту оставил

2023-06-08 23:26 UTC, s-shpak requested changes

2023-06-08 23:26 UTC, s-shpak commented on internal/app/repositories/file.go
> +			logger.Error("Ошибка при попытке иницилизации репозитория", zap.Error(err))
все верно, my bad

2023-06-08 23:26 UTC, s-shpak commented on internal/app/repositories/file.go
> +	} else {
Этот `else` не нужен

2023-06-08 23:26 UTC, s-shpak commented on internal/app/repositories/file.go
> +			logger.Fatal("Ошибка при получения uuid записи", zap.Error(err))
Не стоит вызывать `Fatal` из глубины кода, т.к. это завершить программу. Просто верни ошибку наверх и обработай ее в `main` (вот там и можно вызвать `Fatal`)

2023-06-09 11:16 UTC, s-shpak approved these changes

2023-06-09 12:38 UTC, merged